# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Generate APK"
  lane :generate_apk do
    gradle(task: "clean assembleRelease")
    sh "echo 'assembleRelease completed'"
  end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end

  desc "Build and Deploy Android Release"
  private_lane :android_release do |options|
    flavor = options[:flavor]

    gradle(
      task: "clean bundleRelease",
      # properties: {
      # 	'vcode' => version_code,
      # 	'vname' => next_version
      # }
    )
    upload_to_play_store(
      track: flavor,
      aab: "./app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true,
      # skip_upload_changelogs: true,
      # version_name: "#{version_name}",
    )
  end

  desc "Submit a new Build to Beta Track"
  lane :beta do
    android_release(flavor: "beta")
  end

  desc "Submit a new Release build to Production Track"
  lane :production do
    android_release(flavor: "production")
  end
end
